directories:
  output: release
  buildResources: resources
appId: com.ThomasThanos.SouvlatzidikoUnlocker
productName: Souvlatzidiko-Unlocker
copyright: MIT
files:
  - filter:
      - dist/**/*
      - resources/**/*
      - package.json
extraMetadata:
  main: dist/main/main/index.js
publish:
  provider: github
  owner: ThomasThanos
  repo: steam-idler
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: resources/steam_x256.ico
  requestedExecutionLevel: asInvoker
  signAndEditExecutable: false
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  installerIcon: resources/steam_x256.ico
  uninstallerIcon: resources/steam_x256.ico
  installerHeaderIcon: resources/steam_x256.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Souvlatzidiko-Unlocker
  include: resources/installer.nsh
mac:
  target:
    - dmg
  icon: resources/steam.png
  category: public.app-category.games
linux:
  target:
    - AppImage
    - deb
  icon: resources/steam.png
  category: Game
electronVersion: 28.3.3
