directories:
  output: release
  buildResources: resources
appId: com.ThomasThanos.SouvlatzidikoUnlocker
productName: Souvlatzidiko-Unlocker
copyright: MIT
files:
  - filter:
      - dist/**/*
      - resources/**/*
      - package.json
extraMetadata:
  main: dist/main/main/index.js
publish:
  provider: github
  owner: ThomasThanos
  repo: steam-idler
  releaseType: release
executableName: Souvlatzidiko-Unlocker
extraResources:
  - from: resources/all_steam_x256.ico
    to: all_steam_x256.ico
  - from: resources/notify.png
    to: notify.png
  - from: resources/steam.png
    to: steam.png
artifactName: Souvlatzidiko-Unlocker-Setup.${ext}
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: resources/all_steam_x256.ico
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: true
  perMachine: false
  allowToChangeInstallationDirectory: false
  installerIcon: resources/all_steam_x256.ico
  uninstallerIcon: resources/all_steam_x256.ico
  installerHeaderIcon: resources/all_steam_x256.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Souvlatzidiko-Unlocker
  include: resources/installer.nsh
  warningsAsErrors: false
mac:
  target:
    - dmg
  icon: resources/steam.png
  category: public.app-category.games
linux:
  target:
    - AppImage
    - deb
  icon: resources/steam.png
  category: Game
electronVersion: 28.3.3
